apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: demoentitys.demo.kubeops.dev
spec:
  group: demo.kubeops.dev
  names:
    kind: DemoEntity
    listKind: DemoEntityList
    plural: demoentitys
    singular: demoentity
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          status:
            description: Status object for the entity.
            properties:
              demoStatus:
                type: string
            type: object
          spec:
            description: Specification of the kubernetes object.
            properties:
              username:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}